keys:
  - &host_ age13uqlmzsyxdxxxkvsql7utjeqyt969jdjl6nh6d0gdqdvz6re05fq6t8xge # TODO: Do nix-sops setup
creation_rules:
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *host_turing
  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *host_turing
  - path_regex: hosts/turing/secrets/.*
    key_groups:
      - age:
          - *host_turing
          - *user_maru
